/**
 * robots.txt — generated by Next.js at build time.
 * Accessible at /robots.txt.
 *
 * STRATEGY:
 * Allow all legitimate crawlers to index public content.
 * Block routes that must never be indexed:
 *   - /api/*         → server endpoints, no user-facing content
 *   - /_next/*       → internal Next.js assets (not user-facing)
 *   - /admin/*       → future admin panel (noindex proactively)
 *   - /dashboard/*   → future dealer/user dashboard
 *   - /preview/*     → draft/preview content — not production-ready
 *   - /thank-you     → post-form pages (no SEO value, thin content)
 *
 * CRAWL BUDGET:
 * For a site this size (< 50 pages), crawl budget is rarely a concern.
 * As the vehicle inventory scales to 100s of pages, add a `crawlDelay`
 * for less important bots to avoid server load during peak hours.
 */

import { SITE_URL } from "@/lib/seo/config";

export default function robots() {
  return {
    rules: [
      // ── Main rule: allow all legitimate search engine bots ──────────────────
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/_next/",
          "/admin/",
          "/dashboard/",
          "/preview/",
          "/thank-you",
          "/*?*",            // Block query-string variants (prevents duplicate content)
        ],
      },

      // ── Google: explicit crawl permissions ─────────────────────────────────
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: [
          "/api/",
          "/admin/",
          "/dashboard/",
          "/preview/",
        ],
      },

      // ── Google Image bot: allow vehicle images explicitly ──────────────────
      {
        userAgent: "Googlebot-Image",
        allow: [
          "/Toyota/",
          "/Lexus/",
          "/Mercedes/",
          "/Bmw/",
          "/Bus/",
          "/Electric/",
          "/background/",
          "/Logo/",
          "/Others/",
        ],
      },

      // ── Block AI training crawlers (standard industry practice) ────────────
      {
        userAgent: [
          "GPTBot",
          "ChatGPT-User",
          "CCBot",
          "anthropic-ai",
          "Claude-Web",
          "Bytespider",
          "Omgilibot",
        ],
        disallow: "/",
      },

      // ── Block aggressive SEO scrapers and spam bots ────────────────────────
      {
        userAgent: [
          "SemrushBot",
          "AhrefsBot",
          "MJ12bot",
          "DotBot",
          "BLEXBot",
        ],
        crawlDelay: 10,         // Allow but rate-limit; remove if you pay for these tools
        disallow: ["/api/", "/admin/"],
      },
    ],

    // Primary sitemap reference
    sitemap: `${SITE_URL}/sitemap.xml`,

    // Host directive (used by Yandex to identify canonical domain)
    host: SITE_URL,
  };
}
