/**
 * XML Sitemap — generated by Next.js at build time (or on-demand in dev).
 * Accessible at /sitemap.xml.
 *
 * WHY THIS MATTERS:
 * A well-structured sitemap is the primary signal to Googlebot about which
 * URLs exist, how important they are, and how often they change. Missing URLs
 * in the sitemap can delay indexing by days or weeks for a new site.
 *
 * SCALING:
 * When Supabase powers vehicle inventory, replace the static `vehicleRoutes`
 * array with a DB fetch:
 *
 *   const vehicles = await supabase.from("vehicles").select("slug, updated_at, images");
 *   const vehicleRoutes = vehicles.data.map((v) => ({
 *     url: `${SITE_URL}/showroom/our-vehicles/${v.slug}`,
 *     lastModified: new Date(v.updated_at),
 *     changeFrequency: "daily",
 *     priority: 0.9,
 *     images: v.images?.map((img) => ({ url: img.url, title: img.alt })),
 *   }));
 *
 * IMAGE SITEMAP:
 * The `images` property on each entry is a Google extension to the sitemap
 * protocol. It hints Googlebot about images on the page — important for
 * automotive sites where image search drives significant traffic.
 */

import { SITE_URL, BLOG_SLUGS, SITEMAP_PRIORITIES, PAGE_ROUTES } from "@/lib/seo/config";

// Pinned date used for static pages — update when you do major content refreshes
const SITE_LAUNCH_DATE = new Date("2025-01-01");
const NOW = new Date();

/**
 * Static page definitions with explicit priorities and change frequencies.
 * @type {Array<{route: string, changeFreq: string, lastMod?: Date}>}
 */
const STATIC_PAGES = [
  { route: PAGE_ROUTES.home,          changeFreq: "daily",   lastMod: NOW },
  { route: PAGE_ROUTES.showroom,      changeFreq: "daily",   lastMod: NOW },
  { route: PAGE_ROUTES.latestVehicles,changeFreq: "daily",   lastMod: NOW },
  { route: PAGE_ROUTES.contact,       changeFreq: "monthly", lastMod: SITE_LAUNCH_DATE },
  { route: PAGE_ROUTES.financing,     changeFreq: "monthly", lastMod: SITE_LAUNCH_DATE },
  { route: PAGE_ROUTES.preorder,      changeFreq: "weekly",  lastMod: NOW },
  { route: PAGE_ROUTES.about,         changeFreq: "monthly", lastMod: SITE_LAUNCH_DATE },
  { route: PAGE_ROUTES.blog,          changeFreq: "weekly",  lastMod: NOW },
  { route: PAGE_ROUTES.afterSales,    changeFreq: "monthly", lastMod: SITE_LAUNCH_DATE },
  { route: PAGE_ROUTES.history,       changeFreq: "yearly",  lastMod: SITE_LAUNCH_DATE },
];

/**
 * Representative vehicle inventory entries for the sitemap.
 * In production, replace with a Supabase query.
 *
 * The `images` array tells Google Image Search what's on each page,
 * boosting image-based traffic from searches like "Toyota Camry 2024 photo".
 */
const VEHICLE_ENTRIES = [
  {
    slug: "toyota-camry-2024",
    label: "Toyota Camry 2024",
    image: "/Toyota/Toyota Camry 2024.jpeg",
  },
  {
    slug: "toyota-camry-2025",
    label: "Toyota Camry 2025",
    image: "/Toyota/Toyota Camry 2025.jpeg",
  },
  {
    slug: "toyota-camry-2026",
    label: "Toyota Camry 2026",
    image: "/Toyota/Toyota Camry 2026.jpeg",
  },
  {
    slug: "toyota-highlander-2024",
    label: "Toyota Highlander 2024",
    image: "/Toyota/Toyota Highlander 2024.jpeg",
  },
  {
    slug: "lexus-es-2025",
    label: "Lexus ES 2025",
    image: "/Lexus/Lexus ES 2025.jpg",
  },
  {
    slug: "lexus-gx-2024",
    label: "Lexus GX 2024",
    image: "/Lexus/Lexus GX 2024.jpeg",
  },
  {
    slug: "mercedes-amg-c63-2025",
    label: "Mercedes AMG C63 2025",
    image: "/Mercedes/Mercedes AMG C63 2025.webp",
  },
  {
    slug: "mercedes-s-class-2025",
    label: "Mercedes S Class 2025",
    image: "/Mercedes/Mercedes S Class 2025.jpg",
  },
  {
    slug: "toyota-bz-2025",
    label: "Toyota bZ Electric 2025",
    image: "/Electric/Toyota bZ 2025.jpeg",
  },
  {
    slug: "bmw-i4-2025",
    label: "BMW i4 Electric 2025",
    image: "/Electric/Bmw I4 2025.jpeg",
  },
];

export default function sitemap() {
  // ── Static pages ────────────────────────────────────────────────────────────
  const staticRoutes = STATIC_PAGES.map(({ route, changeFreq, lastMod }) => ({
    url: `${SITE_URL}${route}`,
    lastModified: lastMod,
    changeFrequency: changeFreq,
    priority: SITEMAP_PRIORITIES[route] ?? SITEMAP_PRIORITIES.default,
  }));

  // ── Blog detail pages ────────────────────────────────────────────────────────
  const blogRoutes = BLOG_SLUGS.map((slug) => ({
    url: `${SITE_URL}/showroom/blog/${slug}`,
    lastModified: NOW,
    changeFrequency: "monthly",
    priority: 0.75,
  }));

  // ── Vehicle detail pages with image hints ────────────────────────────────────
  const vehicleRoutes = VEHICLE_ENTRIES.map(({ slug, label, image }) => ({
    url: `${SITE_URL}/showroom/our-vehicles/${slug}`,
    lastModified: NOW,
    changeFrequency: "weekly",
    priority: 0.9,
    // Google Image Sitemap extension — drives image search traffic
    images: [
      {
        url: `${SITE_URL}${image}`,
        title: `${label} for Sale in Nigeria`,
        caption: `${label} — available at Iriseagle. Buy in Lagos, Abuja, Port Harcourt.`,
      },
    ],
  }));

  return [...staticRoutes, ...blogRoutes, ...vehicleRoutes];
}
